'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class animal
    Public Property aniCod As Integer
    Public Property aniCaravana As String
    Public Property razaCod As Nullable(Of Integer)
    Public Property aniSexo As String
    Public Property aniFchNac As Nullable(Of Date)
    Public Property aniEstado As String
    Public Property aniFchIns As Nullable(Of Date)
    Public Property aniUsrIns As Nullable(Of Integer)
    Public Property aniFchUpd As Nullable(Of Date)
    Public Property estCod As Nullable(Of Integer)
    Public Property aniUsrUpd As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property establecimiento As establecimiento
    Public Overridable Property raza As raza
    Public Overridable Property gestacions As ICollection(Of gestacion) = New HashSet(Of gestacion)
    Public Overridable Property gestacions1 As ICollection(Of gestacion) = New HashSet(Of gestacion)
    Public Overridable Property nacimientoes As ICollection(Of nacimiento) = New HashSet(Of nacimiento)
    Public Overridable Property nacimientoes1 As ICollection(Of nacimiento) = New HashSet(Of nacimiento)
    Public Overridable Property vision_pesaje As ICollection(Of vision_pesaje) = New HashSet(Of vision_pesaje)
    Public Overridable Property retiroDets As ICollection(Of retiroDet) = New HashSet(Of retiroDet)
    Public Overridable Property vacunacions As ICollection(Of vacunacion) = New HashSet(Of vacunacion)
    Public Overridable Property ventasDets As ICollection(Of ventasDet) = New HashSet(Of ventasDet)

End Class
