'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class auditoria
    Public Property audId As Long
    Public Property audTabla As String
    Public Property audAccion As String
    Public Property audRegistroId As String
    Public Property audFecha As Date
    Public Property audUsuario As String
    Public Property audLoginSql As String
    Public Property audHost As String
    Public Property audApp As String
    Public Property audDetalleJson As String
    Public Property usuCod As Nullable(Of Integer)

    Public Overridable Property usuario As usuario

End Class
