'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ganaderiaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ganaderiaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property animals() As DbSet(Of animal)
    Public Overridable Property auditorias() As DbSet(Of auditoria)
    Public Overridable Property barrios() As DbSet(Of barrio)
    Public Overridable Property categorias() As DbSet(Of categoria)
    Public Overridable Property ciudades() As DbSet(Of ciudade)
    Public Overridable Property clientes() As DbSet(Of cliente)
    Public Overridable Property comprasCabs() As DbSet(Of comprasCab)
    Public Overridable Property comprasDets() As DbSet(Of comprasDet)
    Public Overridable Property departamentos() As DbSet(Of departamento)
    Public Overridable Property establecimientoes() As DbSet(Of establecimiento)
    Public Overridable Property gastosCabs() As DbSet(Of gastosCab)
    Public Overridable Property gastosDets() As DbSet(Of gastosDet)
    Public Overridable Property gestacions() As DbSet(Of gestacion)
    Public Overridable Property impuestoes() As DbSet(Of impuesto)
    Public Overridable Property nacimientoes() As DbSet(Of nacimiento)
    Public Overridable Property profesionals() As DbSet(Of profesional)
    Public Overridable Property proveedors() As DbSet(Of proveedor)
    Public Overridable Property razas() As DbSet(Of raza)
    Public Overridable Property retiroes() As DbSet(Of retiro)
    Public Overridable Property retiroDets() As DbSet(Of retiroDet)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property tipoAlimentacions() As DbSet(Of tipoAlimentacion)
    Public Overridable Property tipoServicios() As DbSet(Of tipoServicio)
    Public Overridable Property tipoVacunas() As DbSet(Of tipoVacuna)
    Public Overridable Property usuarios() As DbSet(Of usuario)
    Public Overridable Property vacunacions() As DbSet(Of vacunacion)
    Public Overridable Property ventasCabs() As DbSet(Of ventasCab)
    Public Overridable Property ventasDets() As DbSet(Of ventasDet)
    Public Overridable Property vision_dispositivo() As DbSet(Of vision_dispositivo)
    Public Overridable Property vision_modelo() As DbSet(Of vision_modelo)
    Public Overridable Property vision_pesaje() As DbSet(Of vision_pesaje)

End Class
