'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class categoria
    Public Property catCod As Integer
    Public Property catDesc As String

    Public Overridable Property gastosCabs As ICollection(Of gastosCab) = New HashSet(Of gastosCab)

End Class
