'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ciudade
    Public Property ciudCod As Integer
    Public Property ciudNombre As String
    Public Property depaCod As Nullable(Of Integer)

    Public Overridable Property barrios As ICollection(Of barrio) = New HashSet(Of barrio)
    Public Overridable Property departamento As departamento

End Class
