'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cliente
    Public Property clieCod As Integer
    Public Property clieNombre As String
    Public Property clieMarca As String

    Public Overridable Property ventasCabs As ICollection(Of ventasCab) = New HashSet(Of ventasCab)

End Class
