'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class comprasDet
    Public Property cdCod As Integer
    Public Property ccCod As Nullable(Of Integer)
    Public Property cdCantidad As Nullable(Of Integer)
    Public Property cdUnitario As Nullable(Of Decimal)
    Public Property cdTotal As Nullable(Of Decimal)
    Public Property rv As Byte()

    Public Overridable Property comprasCab As comprasCab

End Class
