'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class comprasCab
    Public Property ccCod As Integer
    Public Property provCod As Nullable(Of Integer)
    Public Property ccFch As Nullable(Of Date)
    Public Property estCod As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property establecimiento As establecimiento
    Public Overridable Property proveedor As proveedor
    Public Overridable Property comprasDets As ICollection(Of comprasDet) = New HashSet(Of comprasDet)

End Class
