'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class departamento
    Public Property depaCod As Integer
    Public Property depaNombre As String

    Public Overridable Property ciudades As ICollection(Of ciudade) = New HashSet(Of ciudade)

End Class
