'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class establecimiento
    Public Property estCod As Integer
    Public Property estNombre As String
    Public Property estBarrio As Nullable(Of Integer)

    Public Overridable Property animals As ICollection(Of animal) = New HashSet(Of animal)
    Public Overridable Property barrio As barrio
    Public Overridable Property comprasCabs As ICollection(Of comprasCab) = New HashSet(Of comprasCab)
    Public Overridable Property gestacions As ICollection(Of gestacion) = New HashSet(Of gestacion)
    Public Overridable Property retiroes As ICollection(Of retiro) = New HashSet(Of retiro)
    Public Overridable Property ventasCabs As ICollection(Of ventasCab) = New HashSet(Of ventasCab)

End Class
