'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class gastosCab
    Public Property gcCod As Integer
    Public Property gcDescripcion As String
    Public Property gcFecha As Nullable(Of Date)
    Public Property gcMonto As Nullable(Of Decimal)
    Public Property impCod As Nullable(Of Integer)
    Public Property provCod As Nullable(Of Integer)
    Public Property catCod As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property categoria As categoria
    Public Overridable Property impuesto As impuesto
    Public Overridable Property proveedor As proveedor
    Public Overridable Property gastosDets As ICollection(Of gastosDet) = New HashSet(Of gastosDet)

End Class
