'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class gestacion
    Public Property preCod As Integer
    Public Property aniCodMadre As Nullable(Of Integer)
    Public Property preFchMontura As Nullable(Of Date)
    Public Property preFchConfirma As Nullable(Of Date)
    Public Property preFchparto As Nullable(Of Date)
    Public Property preEstado As String
    Public Property estCod As Nullable(Of Integer)
    Public Property aniCodPadre As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property animal As animal
    Public Overridable Property animal1 As animal
    Public Overridable Property establecimiento As establecimiento

End Class
