'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class impuesto
    Public Property impCod As Integer
    Public Property impDesc As String
    Public Property impDivisor As Nullable(Of Integer)

    Public Overridable Property gastosCabs As ICollection(Of gastosCab) = New HashSet(Of gastosCab)
    Public Overridable Property ventasCabs As ICollection(Of ventasCab) = New HashSet(Of ventasCab)

End Class
