'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class nacimiento
    Public Property nacCod As Integer
    Public Property aniCodMadre As Nullable(Of Integer)
    Public Property nacFch As Nullable(Of Date)
    Public Property nacSexo As String
    Public Property nacEstado As String
    Public Property aniCodCria As Nullable(Of Integer)
    Public Property tsCod As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property animal As animal
    Public Overridable Property animal1 As animal
    Public Overridable Property tipoServicio As tipoServicio

End Class
