'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class proveedor
    Public Property provCod As Integer
    Public Property provNombre As String
    Public Property provMarca As String

    Public Overridable Property comprasCabs As ICollection(Of comprasCab) = New HashSet(Of comprasCab)
    Public Overridable Property gastosCabs As ICollection(Of gastosCab) = New HashSet(Of gastosCab)

End Class
