'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class retiroDet
    Public Property retiDetCod As Integer
    Public Property retiCod As Nullable(Of Integer)
    Public Property aniCod As Nullable(Of Integer)
    Public Property taCod As Nullable(Of Integer)

    Public Overridable Property animal As animal
    Public Overridable Property retiro As retiro
    Public Overridable Property tipoAlimentacion As tipoAlimentacion

End Class
