'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipoAlimentacion
    Public Property taCod As Integer
    Public Property taNombre As String

    Public Overridable Property retiroDets As ICollection(Of retiroDet) = New HashSet(Of retiroDet)

End Class
