'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipoServicio
    Public Property tsCod As Integer
    Public Property tsNombre As String

    Public Overridable Property nacimientoes As ICollection(Of nacimiento) = New HashSet(Of nacimiento)

End Class
