'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuario
    Public Property usuCod As Integer
    Public Property usuLogin As String
    Public Property usuNombre As String
    Public Property usuPass As String
    Public Property usuDescripcion As String
    Public Property usuRol As String
    Public Property usuEmail As String
    Public Property usuFchCrea As Date
    Public Property usuFchMod As Nullable(Of Date)
    Public Property usuActivo As Nullable(Of Integer)

    Public Overridable Property auditorias As ICollection(Of auditoria) = New HashSet(Of auditoria)

End Class
