'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vacunacion
    Public Property vacCod As Integer
    Public Property vacFch As Nullable(Of Date)
    Public Property tvCod As Nullable(Of Integer)
    Public Property vacDosis As Nullable(Of Decimal)
    Public Property profCod As Nullable(Of Integer)
    Public Property aniCod As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property animal As animal
    Public Overridable Property profesional As profesional
    Public Overridable Property tipoVacuna As tipoVacuna

End Class
