'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventasDet
    Public Property vdCod As Integer
    Public Property vcCod As Nullable(Of Integer)
    Public Property vdCantidad As Nullable(Of Integer)
    Public Property vdUnitario As Nullable(Of Decimal)
    Public Property vdTotal As Nullable(Of Decimal)
    Public Property vdPesoProm As Nullable(Of Decimal)
    Public Property aniCod As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property animal As animal
    Public Overridable Property ventasCab As ventasCab

End Class
