'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventasCab
    Public Property vcCod As Integer
    Public Property vcFch As Nullable(Of Date)
    Public Property clieCod As Nullable(Of Integer)
    Public Property impCod As Nullable(Of Integer)
    Public Property estCod As Nullable(Of Integer)
    Public Property rv As Byte()

    Public Overridable Property cliente As cliente
    Public Overridable Property establecimiento As establecimiento
    Public Overridable Property impuesto As impuesto
    Public Overridable Property ventasDets As ICollection(Of ventasDet) = New HashSet(Of ventasDet)

End Class
