'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vision_modelo
    Public Property modId As Integer
    Public Property nombre As String
    Public Property version As String
    Public Property enfoque As String
    Public Property hash As String
    Public Property fechaCarga As Date
    Public Property rowversion As Byte()

    Public Overridable Property vision_pesaje As ICollection(Of vision_pesaje) = New HashSet(Of vision_pesaje)

End Class
