'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vision_pesaje
    Public Property pesId As Long
    Public Property aniCod As Integer
    Public Property fecha As Date
    Public Property pesoKg As Decimal
    Public Property confianza As Nullable(Of Decimal)
    Public Property metodo As String
    Public Property dispId As Nullable(Of Integer)
    Public Property modId As Nullable(Of Integer)
    Public Property imgPath As String
    Public Property medidasJson As String
    Public Property notas As String

    Public Overridable Property animal As animal
    Public Overridable Property vision_dispositivo As vision_dispositivo
    Public Overridable Property vision_modelo As vision_modelo

End Class
